# Generated by Django 5.2.7 on 2025-10-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='high_52_week',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='low_52_week',
        ),
    ]
